### PR TITLE
Drop python 2 from setup

### PR DESCRIPTION
**Pull request by jamesmyatt**
Drop Python 2 support (for simplicity and like sklearn 0.21 and pandas 0.25).
Also test on Python 3.7.

Probably requires a major version bump since pip won't install it on Python <3.5 now.

Note that the notebooks don't run on Python 3 since the future import isn't the first statement.

### CODE REVIEW

**Comment by jamesmyatt** [comment]
Please merge #329 first

**Comment by marcotcr** [comment]
I have to think a bit about whether I am ready to drop python2, as I think a lot of people might still be using it. Thanks though, this will certainly make it much easier if I do go that route now.

**Comment by jamesmyatt** [comment]
numpy (v1.17), pandas (v0.25), scikit learn (v0.21) and matplotlib (v3.0) have all already released versions without Python 2 support. https://python3statement.org/

If you use the `python_requires` keyword in setuptools, then it will guarantee that Python 2.7 will continue to get a compatible version.

**Comment by jamesmyatt** [comment]
2020 is here now. All of the main projects have now stopped making new releases for Python 2. Can this be merged now?

**Comment by marcotcr** [comment]
Yes! Thank you!

**Pull request merged**
