### PR TITLE
random states, discretizers, unit tests, documentation

### PR DESCRIPTION
**Pull request by echo66**
**Changelog**

* random state for discretizers (discretize.py)
* discretizers unit tests (test_discretize.py)
* passing a random state value in the LimeTabularExplainer constructor (lime_tabular.py)
* passing a BaseDiscretizer instance in the LimeTabularExplainer constructor (lime_tabular.py)
* in __data_inverse, replacing np.random.normal and np.random.choice with self.random_state.normal and self.random_state.choice (lime_tabular.py)
* in __data_labels_distances, replacing np.random.randint and np.random.choice with self.random_state.randint and self.random_state.choice (lime_text.py)
* in data_labels, replacing np.random.randint with self.random_state.randint (lime_image.py)
* passing a random state value as a parameter of id_generator method (explanation.py)
* passing a random state value in the RecurrentTabularExplainer constructor (lime_tabular.py)
* passing a BaseDiscretizer instance in the RecurrentTabularExplainer constructor (lime_tabular.py)
* passing a random state value in the LimeBase constructor (lime_base.py)
* passing a random state value to the LimeBase constructor in the LimeTabularExplainer (lime_tabular.py)
* passing a random state value to the LimeBase constructor in the LimeImageExplainer (lime_image.py)
* passing a random state value to the LimeBase constructor in the LimeTextExplainer (lime_text.py)
* analyze all methods in lime_base.py to see if any constructors being used allow a random state value to be passed as parameter. EDIT: found several lines using the sklearn.linear_model.Ridge constructor. (lime_base.py)
* fix the LimeImageExplainer constructor documentation (lime_image.py)
* set random_seed parameter for the skimage.segmentation.quickshift algorithm
* add scikit-image to setup.py
* add TODO to specific docstrings so LIME maintainers know that they need to describe that better (sorry, I'm new to LIME)
* unit tests to check if the same random state produces the same explanations using different LimeTabularExplainer instances
* unit tests to check if the same random state produces the same explanations using different LimeTextExplainer instances

### CODE REVIEW

**Comment by echo66** [comment]
Did I do something wrong??? All unit tests are green..

**Comment by marcotcr** [comment]
Hey, thanks for the PR. If you click on 'details', travis shows you what failed. In this case, it was all flake8 stuff:
```$ flake8 lime
lime/lime_tabular.py:418:47: E128 continuation line under-indented for visual indent
lime/lime_tabular.py:570:49: W292 no newline at end of file
lime/lime_text.py:331:39: W292 no newline at end of file
lime/tests/test_lime_tabular.py:477:1: E305 expected 2 blank lines after class or function definition, found 1
lime/tests/test_lime_text.py:79:101: E501 line too long (101 > 100 characters)
lime/tests/test_lime_text.py:82:101: E501 line too long (101 > 100 characters)
lime/tests/test_lime_text.py:103:101: E501 line too long (105 > 100 characters)
lime/tests/test_lime_text.py:106:101: E501 line too long (105 > 100 characters)
lime/tests/test_lime_text.py:110:1: E305 expected 2 blank lines after class or function definition, found 1
```

**Comment by marcotcr** [comment]
Quick question: do you plan on fixing the flake8 stuff? : )

**Comment by echo66** [comment]
Hi Marco! Yes, I do. I just had two hard working weeks. I will get back at this tomorrow. Is it just a code style thing?

**Comment by marcotcr** [comment]
yes!

**Comment by echo66** [comment]
I fixed the style issues but the building process is still failing. For all python versions in travis, this seems to be where the problem is at:

The command "flake8 lime" exited with 1.

**Comment by jcmuddle** [comment]
From the raw log, there is the following flake8 issue:
lime/lime_tabular.py:570:45: W292 no newline at end of file

**Comment by jcmuddle** [comment]
@echo66 your welcome.

**Comment by echo66** [comment]
@marcotcr it seems that the remaining issue with travis is something related to the previous commit you made (in the unit tests for the Iris dataset).

**Comment by echo66** [comment]
All ready to go

**Comment by marcotcr** [comment]
Thanks a lot! This is helpful.

**Pull request merged**
