### PR TITLE
submodular pick for LimeTabularExplainer

### PR DESCRIPTION
**Pull request by dyanni3**
In reference to issue [#60](https://github.com/marcotcr/lime/issues/60), this pull request adds a method submodular_pick to the LimeTabularExplainer object based on your paper and the greedy code you linked to in the Issues.

This is my first contribution to an open source project so please excuse my etiquette if I missed something.

Finally, thanks so much for LIME!

### CODE REVIEW

**Comment by marcotcr** [comment]
Thanks for the PR, and sorry for the delay in responding.
I like how you have an option for subsampling the data before computing explanations. Would you mind making the following two small changes?
1. Use lowercase variable names, unless it's for stuff like W or V. 
2. Make submodular_pick into a class of its own. I think your implementation works for both TabularExplainer and TextExplainer. Just make the explainer one of the parameters, and pass explain_instance params through **kwargs. This would also allow you to save all of the computed explanations. I think if we're computing a bunch of explanations, we should keep them saved by default (even if they are not in the top K)

If you can't, I'll take your code and do the changes myself, but I'll probably take longer

Again, thanks!

**Comment by dyanni3** [comment]
How does this look?

Thanks again for creating LIME!

**Comment by marcotcr** [comment]
It looks really good, thank you for making the changes!
I couldn't run the regression part of the notebook though, I got the top_labels error. Since that comment is crossed off here, did you fix it somehow and forgot to push the change?

**Comment by dyanni3** [comment]
Yes, you are right! 

Sorry about that. The fix is a bit of a kluge, but it is working for me now on the test notebook.

**Comment by marcotcr** [comment]
Thanks again!

**Pull request merged**
