### PR TITLE
Fixed deprecated scikit-learn reference

### PR DESCRIPTION
**Pull request by mrandrewandrade**
This fixes the warnings for deprecated API references.  I also ran the notebook fresh and remove the empty cell at the end.

### CODE REVIEW

**Comment by mrandrewandrade** [comment]
@marcotcr  Let me know if you need any changes made

**Comment by marcotcr** [comment]
Sorry, it's basically impossible to look at a notebook diff.
Is the difference sklearn.cross_validation  => sklearn.model_selection ?

**Comment by mrandrewandrade** [comment]
@marcotcr That's the one!

Also since it's impossible to look at a notebook diff have you considered putting your examples in .py files instead of notebooks?  It makes it much more readable and maintainable.

**Comment by mrandrewandrade** [comment]
I'm happy to contribute another PR with this.

**Pull request merged**
