### PR TITLE
Fixed PR for empty rows during submodular pick

### PR DESCRIPTION
**Pull request by Romits**
While loading large datasets during sub-modular pick, empty row in the dataset was causing the entire code to crash. Fixed the code to handle the issue.

### CODE REVIEW

**Comment by Romits** [comment]
Below is the error message which appears without the above fix.
 in __data_labels_distances
    sample = self.random_state.randint(1, doc_size + 1, num_samples - 1)
  File "mtrand.pyx", line 993, in mtrand.RandomState.randint
ValueError: low >= high

**Comment by marcotcr** [comment]
Is this a bug in lime_tabular or lime_text? I'm guessing lime_text? if that is the case, it's better to fix the problem where it is (i.e. return empty explanation when input is empty). Although in this case I'm not even sure if that is a bug, the input is malformed.

**Comment by Romits** [comment]
This bug is in lime_text. I got this error with certain subset of standard 20 newsgroup dataset which is not large dataset for deep learning. Also  even for clean datasets very often we end up having empty records due to various reasons which causes code to crash. The fix takes care of scenarios even when inputting slices.

**Comment by marcotcr** [comment]
Cool, so this is not the fix.
Thanks,

**Pull request closed without merging**
