### PR TITLE
Regression support

### PR DESCRIPTION
**Pull request by Aylr**
I took @aikramer2's work in #52 and made the following minor changes to satisfy flake8:

- synced the branch with the latest `master` from the base project
- new `LimeError` class
- lots of formatting (mostly lines that were >79
- removed two unused `labels` variables.

### CODE REVIEW

**Comment by desilinguist** [comment]
I have never really worked on a project with people who aren't collaborators on the same repository. So, how would this work? Do I fork @Aylr's fork and then submit a PR to his `regression-support` branch?

**Comment by Aylr** [comment]
It does add some complexity, but yes, fork my fork (which was forked from @aikramer2's). It works fine, then you can submit a PR from your fork. Or, if you'd prefer I can add you as a collaborator on my repo.

**Comment by desilinguist** [comment]
Okay, I will try the fork-of-the-fork approach first :)

**Comment by desilinguist** [comment]
@Aylr I just made the changes that @marcotcr had suggested to @aikramer2 along with some other ones. I submitted a PR to your fork's branch. I guess you can review it and then merge it such that it shows up in this PR and then @marcotcr can review it too?

**Comment by Aylr** [comment]
@desilinguist Alright, quick work! I have it merged in. FYI I think you could submit a PR to the original project.

Stoked to get this going!

**Comment by desilinguist** [comment]
I see I need to fix some flake issues. I can do that. However, I am a little bit confused about how to do that at this point. @Aylr perhaps you can just make me a collaborator on your lime fork and then I can push directly to this branch? Or is there another option?

**Comment by Aylr** [comment]
Lol, I couldn't resist. I fixed them.

For the future, if we run into a situation like this we should just work on the same repo, or your could fix them then submit the PR to the original repo rather than my fork of a fork. :smile:

**Comment by Aylr** [comment]
I also made you a contributor on my fork if we need to.

**Comment by desilinguist** [comment]
Thanks @Aylr! I appreciate it. I think we need to add some tests to this PR next to make sure the regression stuff is working as expected. I can try to work on that next but it would be nice if @marcotcr  took a look at the changes to make sure everything looks kosher.

**Comment by Aylr** [comment]
@desilinguist Agreed. Let's let @marcotcr review it first.

**Comment by aikramer2** [comment]
great stuff! thanks for taking this on.

**Comment by marcotcr** [comment]
I'll try to look at this tomorrow. Thanks guys

**Comment by marcotcr** [comment]
Made minor changes and merged it. Thanks guys.

**Comment by desilinguist** [comment]
Thanks for merging this @marcotcr. Do you think we need to add some tests for the regression case in a new PR or did you test it locally and are satisfied that it works as expected?

**Comment by Aylr** [comment]
...and once you @marcotcr are happy we should update the readme so show regression examples and probably get rid of the outdated regression prototype notebook.

**Comment by marcotcr** [comment]
I updated the [notebook](https://marcotcr.github.io/lime/tutorials/Using%2Blime%2Bfor%2Bregression.html) without much explanation, and added it to the readme.

**Comment by Aylr** [comment]
Rad!

**Pull request merged**
