### PR TITLE
Lime image segmentation issue 109

### PR DESCRIPTION
**Pull request by FlorentPajot**
Tested on Python 2.6 and 3.2 with different versions of Scikit-image (0.12, 0.13). I added a certain amount of work to make the wrapper class usable for next improvements (like wrapping Scikit-learn algorithm to allow user modify the model used to make the local approximation). Unit tests use built-in unittest, and the syntax enforce PEP8 rules.

### CODE REVIEW

**Comment by marcotcr** [comment]
Thanks a lot for this, and sorry for taking so long to respond.
The code looks fine, but the changes to the ipynb tutorials are too large to review, and not all of them seem needed. Would you mind changing the diffs for the notebooks so that they include only necessary changes?

**Comment by FlorentPajot** [comment]
Actually I don't know exactly why they are so many changes in the notebooks, I changed only a few lines but it automatically changed some metatdata which are not relevant (may due to the fact that I use a different version of IPython than yours). I'll try to undo the commits related to notebokos and just give you the lines where there is a change...

**Comment by FlorentPajot** [comment]
OK I made the changes to notebook files. I just changed the important lines. You'll just have to check it works fine.

**Comment by marcotcr** [comment]
Thanks! sorry for the long delay

**Pull request merged**
