### PR TITLE
Dimension scaled kernel

### PR DESCRIPTION
**Pull request by wdm0006**
Here is the PR I mentioned with the kernel function scaled by input data dimension. It doesn't add any overhead for the user and seems to qualitatively make the difference between different distance metrics less extreme and the impact of kernel widths more predictable. 

Let me know if you think it'd be good to fold in.

### CODE REVIEW

**Comment by marcotcr** [comment]
Sorry for the long delay, I just haven't had the time to try this with different datasets. I'll do this when I come back from a conference.
Thanks!

**Comment by marcotcr** [comment]
Sorry to get back to this so late. So, did you find that keeping the same default width (3) while still dividing it by the number of features worked well on most cases? I initially came to the width=3 value by playing around with small-sized datasets (8-10 columns), and if I remember correctly having 0.3 (3/10) would be too small.

**Comment by wdm0006** [comment]
Yeah, I've seen similar things, we're this merged it would probably make sense to change the default width to 25-30 to compensate.

**Comment by marcotcr** [comment]
Thanks for this idea. In order to keep the kernel the same (so that people can reason about it more easily), I changed the default parameter of kernel_width instead of changing the kernel function in [this commit](https://github.com/marcotcr/lime/commit/976695bf6e2f246e61dbbac12922cd71e87c0faa). IfI also changed the scaling so that it is according to sqrt(K) instead of K (where K is the number of columns), as I think euclidean distance grows at a sqrt rate instead of a K rate usually.

**Comment by wdm0006** [comment]
Makes sense, thanks!

**Pull request closed without merging**
